import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header/index';
import Preloader from '@/components/Preloader/index';

export const metadata: Metadata = {
    title: "SNS",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <Preloader />
        <Header />
        {children}
        </body>
        </html>
    );
}
